project:
  name: "high_q_meta_transformer"
  dataset_dir: "dataset"
  output_csv: "dataset/qBIC_spectral_data.csv"

simulation:
  wavelength_start_nm: 3000
  wavelength_end_nm: 9000
  wavelength_points: 1000
  mesh_accuracy: 3

dataset:
  num_samples: 1 # remove 12600 for test
  test_size: 0.20
  batch_size: 32
  random_seed: 42

model:
  num_parameters: 5
  learning_rate: 0.001
  epochs: 1000
  spec_vit:
    embed_dim: 64
    depth: 6
    num_heads: 8
  meta_vit:
    embed_dim: 128
    depth: 6
    num_heads: 8
    dim_feedforward: 128